var objects = {
  'letters':{
    'a': ['a','aye','hey'],
    'b': ['b','be','bee'],
    'c': ['c','see','sea'],
    'd': ['d','teen','the','t'],
    'e': ['e','i'],
    'f': ['f','if'],
    'g': ['g','she'],
    'h': ['h'],
    'i': ['i'],
    'j': ['j','jay'],
    'k': ['k'],
    'l': ['l','el','how'],
    'm': ['m','and'],
    'n': ['n','and'],
    'o': ['o','oh'],
    'p': ['p','b'],
    'q': ['q','you','cute'],
    'r': ['r','ar','are','bar'],
    's': ['s','has'],
    't': ['t','tea'],
    'u': ['u','you'],
    'v': ['v','g','the','free','movie','we','me'],
    'w': ['w'],
    'x': ['x','axe'],
    'y': ['y','why'],
    'z': ['z','the'],
  }
};